version: "3"
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # working_dir: /workspace
  #   volumes:
  #     - ..:/api:delegated
  #     - node_modules:/api/node_modules
  #   tty: true
  #   depends_on:
  #     - db
  db:
    image: mysql:8.0
    container_name: mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
volumes:
  # node_modules:
  mysql-data: